### ISSUE TITLE
Static compilation with musl not succeeded

### ISSUE THREAD

**Issue by freedeaths** [georust/proj#66]
# Question: Is it possible to compile the application statically with MUSL or other tools/methods? The application needs so many dependencies that it is not esay to deploy.

I have attemped:

1. Compiled exmaple successful;

```rust
use proj::Proj;

extern crate geo_types;
use geo_types::Point;

fn main() {
    let from = "EPSG:2230";
    let to = "EPSG:26946";
    let ft_to_m = Proj::new_known_crs(&from, &to, None).unwrap();
    let result = ft_to_m
        .convert(Point::new(4760096.421921, 3744293.729449))
        .unwrap();
    println!("{}", result.x() as f64);
    println!("{}", result.y() as f64);
    //assert_approx_eq::assert_approx_eq!(result.x() as f64, 1450880.2910605003);
    //assert_approx_eq::assert_approx_eq!(result.y() as f64, 1141263.0111604529);
}
```

```toml
[package]
name = "testproj"
version = "0.1.0"
authors = ["freedeaths"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proj = { version = "0.20.5", features = ["bundled_proj"] }
assert_approx_eq = "1.1"
geo-types = "0.6"
```

I could run this application in PC where I compiled in. *BUT* I can't send this binary to other pc which says "cannot find proj.db and balabala" after run this binary.

2. Compiled this project as proj.rlib or proj.a successful(wrapped with libproj.a generated);

3. Fail to compiled the application 1 with musl on Ubuntu Server 18.04 and got ERROR like:

> undefined reference to `__dso_handle
>
> undefined reference to `__cpu_indicator_init'
>
> undefined reference to `__cpu_model'

```bash
sudo apt install musl-tools
rustup target add x86_64-unknown-linux-musl
CC=musl-gcc cargo build --release --target=x86_64-unknown-linux-musl
```

4. Fail to compiled the application 1 with generated proj.a/proj.rlib in step 2, and got ERROR like

```
Package proj was not found in the pkg-config search path.
  Perhaps you should add the directory containing `proj.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'proj' found
  Package proj was not found in the pkg-config search path.
  Perhaps you should add the directory containing `proj.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'proj' found
```
